theme: minima
title: jvnteran's BI Projects/ Proyectos BI
description: This is my Github Pages Landing page for my Business Intelligence / Esta es mi Página de Github Pages donde subo mis proyectos de BI
author: jvnteran
